### ISSUE TITLE
aptly-cli snapshot_list --all

### ISSUE THREAD

**Issue by sepulworld** [sepulworld/aptly_cli#69]
Bug with aptly-cli snapshot_list

```
$ aptly-cli snapshot_list --sort all --trace
/Users/zanew/.rvm/gems/ruby-2.2.1/gems/aptly_cli-0.1.8/lib/aptly_snapshot.rb:25:in `snapshot_list': wrong number of arguments (2 for 0..1) (ArgumentError)
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/aptly_cli-0.1.8/bin/aptly-cli:314:in `block (2 levels) in <top (required)>'
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/zanew/.rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by sepulworld** [comment]
fixed in #70
